### ISSUE TITLE
Consulta Práctica @pedroprieto

### ISSUE THREAD

**Issue by ManuelSolerVilar** [ManuelSolerVilar/Proyecto_Abogados#1]
He conseguido preparar la práctica hasta el punto 3.5.
Con tema económico aun me estoy peleando, espero terminarlo mañana mismo. 
Cuando tenga un hueco, agradecería me diga todo lo que considera oportuno que puedo mejorar. Sin otro particular agradeciendo su tiempo reciba un cordial saludo.

**Comment by pedroprieto** [comment]
Buenas Manuel,

Te contesto por correo. Un saludo!

**Comment by pedroprieto** [comment]
Buenas Manuel,

Está bastante bien. Algunos puntos:

- Sigues utilizando un modelo de negocio "llave en mano": es decir, tu
modelo de negocio se basa en implementar un producto distinto e
independiente para cada cliente. Frente a eso tienes la posibilidad de
crear un portal único a compartir entre todos los despachos. Cada despacho
tendría su área diferenciada vía inicio de sesión. En este último caso
podrías proporcionar un modelo de cuota mensual o pago por uso. Así
consigues que los clientes no tengan que hacer un gran desembolso inicial y
en su lugar paguen un poco cada mes. A efectos de evolución y mantenimiento
de la aplicación la cosa se simplifica también, ya que tendrías una única
aplicación, no muchas distintas.
- El modelo de base de datos está incompleto: no aparecen los tipos de
usuarios (administradores, etc.) ni los contenidos de los que hablas en el
diagrama de casos de uso.

Con respecto al modelo de negocio depende de tu elección, claro está; con
respecto a la base de datos puedes intentar darle una vuelta a ver si
puedes añadir la información que falta. Igual puedes hacer un modelo
Entidad - Relación antes de pasar a las tablas del modelo relacional.

Un saludo,

Pedro Prieto

**Comment by pedroprieto** [comment]
Perdón, al contestar por correo se ha añadido el mensaje aquí. Perdona por la confusión.
