### ISSUE TITLE
Cambios económicos del proyecto @pedroprieto

### ISSUE THREAD

**Issue by ManuelSolerVilar** [ManuelSolerVilar/Proyecto_Abogados#2]
Hola Pedro,
He vuelto a revisar la orientación del proyecto, intentando hacerlo lo más atractivo posible.
Los cambios que se me han ocurrido son los siguientes.
En primer lugar olvidarme de sacar un producto por encima de la media del precio del mercado, llegando al punto que esta un poco por debajo. 
Sacando nuevas cuentas y ajustando todo. He pasado de un precio de más de 2200 € a un precio de 1150€. Que me parece que puede ser muy competitivo.
He elaborado el esquema del diseño conceptual de datos para ver si le puedes echar un vistazo antes de hacer las tablas. 
Y he mejorado el esquema de los casos de uso incluyendo todas las acciones  que se dicen en los requisitos.
Y volví a hacer el punto 3.6 Estimación de ingresos y precios de venta.
No se muy bien si haciendo esto, abre mejorado el planteamiento de la aplicación.
¿Sería posible quedar algún día y tener una tutoría personal?
Sin otro particular, agradeciendo su tiempo reciba un cordial saludo.

**Comment by pedroprieto** [comment]
Buenas Manuel,

El modelo de datos me parece correcto para el caso que tú planteas (una
aplicación por cliente).

Tengo una duda con respecto al servicio de chat: ¿a qué te refieres
exactamente? ¿A la posibilidad de chatear con un abogado (persona)? ¿O a un
chat automatizado que responda las preguntas más frecuentes? Lo primero
sería un chat convencional (lo que tú llamas "chatbox") y lo segundo se
llama "chatbot". La segunda opción normalmente utiliza algún algoritmo de
inteligencia artificial y es autónomo (contesta una máquina, para
entendernos). Tanto si vas a usar una opción como la otra deberías unificar
la terminología (no hablar de "chatbot" si no vas a utilizar esa
tecnología).

Con respecto al modelo de negocio, lo que te comenté era un modelo
alternativo. En tus otros correos me has preguntado a qué me refería: se
trataría de tener una única plataforma para todo el mundo. En ella se
autenticarían abogados y clientes por igual, independientemente del
despacho de abogados al que pertenecieran. Internamente la aplicación
gestionaría los distintos despachos asociados de manera que los abogados
solo tengan acceso a los datos de sus clientes. Lo que tú planteas son
modelos llave en mano. Aunque la personalización sea distinta y el código
el mismo, al final planteas instalar una aplicación para cada despacho.
Necesitarías también un servidor para cada despacho, tanto si es interno en
la empresa como gestionado por ti. Eso te ata a un pago único por
aplicación (es posible que luego puedas completar con algún servicio de
mantenimiento/mejora, con cuota mensual). La alternativa que te proponía es
la de pago por suscripción.

Para entendernos, te propongo una analogía de correo electrónico:
- Tú propones instalar un servidor de correo para cada empresa. La empresa
pagaría una cantidad (2000€) y tú le instalarías la aplicación. Cada
usuario de la empresa se conectaría a su servidor.
- Yo te propongo algo tipo GMail empresarial. La empresa pagaría una
suscripción mensual (20€/mes) en función del número de usuarios que tenga
(abogados) y todo el mundo accedería a través del mismo portal.

No tendrías que buscar clientes para los abogados ni nada. Simplemente el
despacho le diría a los clientes que para acceder a los servicios se tienen
que conectar al servicio de gestión.

Si vas a emplear el modelo que te propongo tendrías que modificar el modelo
entidad relación para gestionar los distintos despachos, ya que habría que
controlar qué abogados y qué clientes forman parte de cada despacho.

Tu modelo de negocio implica mantener varias aplicaciones aunque tengan el
mismo código: tendrías que actualizar la aplicación en varios sitios,
gestionar varios servidores, etc.

De todos modos, la decisión última es tuya.

Un saludo!
