### ISSUE TITLE
Entrega parcial @pedroprieto

### ISSUE THREAD

**Issue by ManuelSolerVilar** [ManuelSolerVilar/Proyecto_Abogados#3]
Buenas tardes Pedro, como te comente ayer, te adjunto el documento de la memoria GestordeDespachosV2, en el podrás observar que he cambiado su orientación hacia el servicio de pago por uso.
Los cambios más significativos han sido en la parte económica, puesto que ahora los clientes pagan 50€ al mes por servicio. 
En el esquema Entidad-Relación que le he incluido el campo abogados y el campo fechas. ¿Lo he puesto en horizontal y queda un poco pequeño. ¿Lo dejo así? ¿O lo vuelvo a poner en vertical?
Hay una parte que verás que la he dejado en verde, esa parte no la he modificado, lo he dejado así para intentar facilitarte un poco la revisión.
En el punto 3.9  hay un boceto de web en grises, que más adelante verás modificado en la página 31. El bueno o la idea es el de la página 31. ¿Que te parece el de la página 31, te parece bien?
Se que tengo que pulir y presentar mejor muchas parte de la memoria, pero creo que para que me puedas orientar esta entrega puede ser suficiente.
Sin otro particular agradeciendo tu tiempo recibe un cordial saludo.

**Comment by pedroprieto** [comment]
Buenas Manuel,

Algunos comentarios:

- En los casos de uso de administrador de software te falta la gestión y
alta de despachos y designación de abogados-gerentes.
- No entiendo muy bien el campo fechas. Entiendo que cada actuación tiene
una fecha, ¿no? ¿O puede tener varias fechas? No me queda claro...
- Puedes poner el E/R en horizontal sin ningún problema, pero solo esa
página (el resto en vertical).
- El boceto me parece muy bueno. Buen trabajo.

Te quedaría terminar un poco el formato, como tú dices, y revisar un poco
el estilo del texto. Lo demás está casi listo.

Ánimo y un saludo!
