### ISSUE TITLE
Entrega Memoria @pedroprieto

### ISSUE THREAD

**Issue by ManuelSolerVilar** [ManuelSolerVilar/Proyecto_Abogados#4]
Buenas tardes Pedro,
Te paso la memoria a falta de retocar la parte visual. 
De lo que me preguntaste de las fechas, si pueden haber varias fechas a la vez en cada actuación.
Creo si no he repasado mal, que me falta el punto 3.2 Elaboración de un guión de trabajo para el desarrollo del proyecto. Lo volveré a repasar con las memorias de los compañeros e intentaré implementarlo.
Del resto creo que esta todo.
Gracias por tu tiempo un saludo.

**Comment by pedroprieto** [comment]
Buenas Manuel,

Está bastante bien. Revísala de nuevo con el corrector ortográfico porque hay alguna errata.

En cuanto a las fechas, lo veo bien, aunque el nombre "fecha" en la entidad del E/R lo veo poco apropiado. Igual sería mejor cambiarlo por "actuacionActo" o algo así...

Buen trabajo!! :clap:
