### ISSUE TITLE
Práctica memoria finalizada @pedroprieto

### ISSUE THREAD

**Issue by ManuelSolerVilar** [ManuelSolerVilar/Proyecto_Abogados#5]
Hola Pedro,
Creo que tengo  terminada la memoria, cuando puedas agradecería me revises el punto
 4.3.Desarrollo programación entorno cliente que lo he ampliado. Y mires el resto haber si ves algo raro.
Sin otro particular agradeciendo tu tiempo, recibe un cordial saludo.

**Comment by pedroprieto** [comment]
Buenas Manuel,

Está muy bien. Todo parece correcto.

Un único punto: no existe CSS4 (pág. 41). La tecnología se llama CSS a secas. Lo que se conoce como CSS4 es la versión 4 de la especificación de algún módulo CSS.

Buen trabajo!
